package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi2"
	"github.com/getkin/kin-openapi/openapi2conv"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
	"go.yaml.in/yaml/v4"

	"github.com/rendis/senda/config"
	sendahttp "github.com/rendis/senda/internal/http"
	"github.com/rendis/senda/internal/http/handler"
)

// Route is the normalized route shape used by the OpenAPI tooling.
type Route struct {
	Method     string
	Path       string
	Parameters []string
}

// RegisteredRoutes returns the full HTTP surface registered by the Echo server.
func RegisteredRoutes() ([]Route, error) {
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelError}))
	cfg := &config.Config{
		Server: config.ServerConfig{
			Host: "0.0.0.0",
			Port: 8080,
		},
	}

	srv := sendahttp.NewServer(cfg, logger,
		sendahttp.WithAuthDeps(nil, nil, nil, ""),
		sendahttp.WithTenantStore(nil),
		sendahttp.WithWorkspaceStore(nil),
		sendahttp.WithPinger(nil),
		sendahttp.WithTenantHandler(&handler.TenantHandler{}),
		sendahttp.WithWorkspaceHandler(&handler.WorkspaceHandler{}),
		sendahttp.WithMemberHandler(&handler.MemberHandler{}),
		sendahttp.WithConfigHandler(&handler.ConfigHandler{}),
		sendahttp.WithInjectorHandler(&handler.InjectorHandler{}),
		sendahttp.WithAdapterHandler(&handler.AdapterHandler{}),
		sendahttp.WithIdentityHandler(&handler.IdentityHandler{}),
		sendahttp.WithAdapterSetupHandler(&handler.AdapterSetupHandler{}),
		sendahttp.WithTemplateTypeHandler(&handler.TemplateTypeHandler{}),
		sendahttp.WithTemplateHandler(&handler.TemplateHandler{}),
		sendahttp.WithSendHandler(&handler.SendHandler{}),
		sendahttp.WithEmailHandler(&handler.EmailHandler{}),
		sendahttp.WithDataPlaneEmailHandler(&handler.DataPlaneEmailHandler{}),
		sendahttp.WithSuppressionHandler(&handler.SuppressionHandler{}),
		sendahttp.WithAuditHandler(&handler.AuditHandler{}),
		sendahttp.WithSESWebhookHandler(&handler.SESWebhookHandler{}),
		sendahttp.WithWebhookHandler(&handler.WebhookHandler{}),
		sendahttp.WithOnboardingHandler(&handler.OnboardingHandler{}),
		sendahttp.WithAPIKeyHandler(&handler.APIKeyHandler{}),
		sendahttp.WithDashboardHandler(&handler.DashboardHandler{}),
		sendahttp.WithTrackingHandler(&handler.TrackingHandler{}),
		sendahttp.WithMediaHandler(&handler.MediaHandler{}),
	)

	routes := srv.Echo().Router().Routes()
	result := make([]Route, 0, len(routes))
	seen := make(map[string]struct{}, len(routes))
	for _, r := range routes {
		if r.Method == echo.RouteNotFound || r.Method == httpMethodOptions || r.Method == httpMethodHead {
			continue
		}
		key := r.Method + " " + r.Path
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		result = append(result, Route{
			Method:     strings.ToUpper(r.Method),
			Path:       r.Path,
			Parameters: append([]string(nil), r.Parameters...),
		})
	}

	sort.Slice(result, func(i, j int) bool {
		if result[i].Path == result[j].Path {
			return result[i].Method < result[j].Method
		}
		return result[i].Path < result[j].Path
	})

	return result, nil
}

const (
	httpMethodHead    = "HEAD"
	httpMethodOptions = "OPTIONS"
)

// NormalizeEchoPath converts Echo route params (:id) to OpenAPI params ({id}).
func NormalizeEchoPath(path string) string {
	parts := strings.Split(path, "/")
	for i, part := range parts {
		if strings.HasPrefix(part, ":") {
			parts[i] = "{" + strings.TrimPrefix(part, ":") + "}"
		}
	}
	return strings.Join(parts, "/")
}

// GenerateSwagDocsContent returns the generated Swag annotations used as input to swag init.
func GenerateSwagDocsContent(routes []Route) string {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by cmd/openapi generate-docs; DO NOT EDIT.\n")
	buf.WriteString("package main\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"github.com/rendis/senda/internal/http/request\"\n")
	buf.WriteString("\t\"github.com/rendis/senda/internal/http/response\"\n")
	buf.WriteString(")\n\n")
	buf.WriteString("var (\n")
	buf.WriteString("\t_ = request.SendEmailRequest{}\n")
	buf.WriteString("\t_ = response.ErrorResponse{}\n")
	buf.WriteString(")\n\n")
	buf.WriteString("type DocGenericBody struct{}\n\n")
	buf.WriteString("type DocGenericObject struct{}\n\n")
	buf.WriteString("type DocErrorDetail struct {\n\tCode string `json:\"code\"`\n\tMessage string `json:\"message\"`\n\tRequestID string `json:\"request_id,omitempty\"`\n}\n\n")
	buf.WriteString("type DocErrorResponse struct {\n\tError DocErrorDetail `json:\"error\"`\n}\n\n")
	buf.WriteString("type DocHealthResponse struct {\n\tStatus string `json:\"status\"`\n\tError string `json:\"error,omitempty\"`\n}\n\n")
	buf.WriteString("type DocStatusResponse struct {\n\tStatus string `json:\"status\"`\n}\n\n")
	buf.WriteString("type DocTemplateLocaleListResponse struct {\n\tItems []response.TemplateVersionLocaleResponse `json:\"items\"`\n}\n\n")
	writef := func(format string, args ...any) {
		_, _ = fmt.Fprintf(&buf, format, args...)
	}

	for _, route := range routes {
		op := buildOperationDoc(route)
		fnName := operationFuncName(route)

		writef("// %s auto-generated route documentation.\n", fnName)
		writef("// @Summary      %s\n", op.Summary)
		buf.WriteString("// @Description  Auto-generated route stub for OpenAPI + MCP discovery.\n")
		writef("// @Tags         %s\n", op.Tag)
		if op.AcceptJSON {
			buf.WriteString("// @Accept       json\n")
		}
		if op.Produce != "" {
			writef("// @Produce      %s\n", op.Produce)
		}
		for _, sec := range op.Security {
			writef("// @Security     %s\n", sec)
		}
		for _, param := range op.Params {
			writef("// @Param        %s  %s  %s  %t  %q\n",
				param.Name, param.In, param.Type, param.Required, param.Description)
		}
		if op.BodyType != "" {
			writef("// @Param        body  body  %s  %t  %q\n",
				op.BodyType, op.BodyRequired, "Request body")
		}
		writef("// @Success      %d  {%s}  %s\n", op.SuccessStatus, op.SuccessKind, op.SuccessType)
		for _, failure := range []int{400, 401, 403, 404, 409, 422, 500} {
			writef("// @Failure      %d  {object}  DocErrorResponse\n", failure)
		}
		writef("// @Router       %s [%s]\n", NormalizeEchoPath(route.Path), strings.ToLower(route.Method))
		writef("func %s() {}\n\n", fnName)
	}

	return buf.String()
}

type operationParam struct {
	Name        string
	In          string
	Type        string
	Required    bool
	Description string
}

type operationDoc struct {
	Summary       string
	Tag           string
	Produce       string
	AcceptJSON    bool
	BodyType      string
	BodyRequired  bool
	SuccessStatus int
	SuccessKind   string
	SuccessType   string
	Security      []string
	Params        []operationParam
}

func buildOperationDoc(route Route) operationDoc {
	normalized := NormalizeEchoPath(route.Path)
	doc := operationDoc{
		Summary:       fmt.Sprintf("%s %s", route.Method, normalized),
		Tag:           routeTag(route),
		Produce:       "json",
		AcceptJSON:    routeHasBody(route),
		BodyType:      routeRequestType(route),
		BodyRequired:  routeHasBody(route),
		SuccessStatus: routeSuccessStatus(route),
		SuccessKind:   "object",
		SuccessType:   routeSuccessType(route),
		Security:      routeSecurity(route),
		Params:        routeParameters(route),
	}

	if doc.BodyType == "" && doc.AcceptJSON {
		doc.BodyType = "DocGenericBody"
	}

	switch normalized {
	case "/metrics":
		doc.Produce = "plain"
		doc.SuccessKind = "string"
		doc.SuccessType = "string"
	case "/t/o/{tracking_id}", "/public/video-thumbnail":
		doc.Produce = "plain"
		doc.SuccessKind = "string"
		doc.SuccessType = "string"
	case "/health", "/healthz":
		doc.SuccessType = "DocHealthResponse"
	}

	return doc
}

func routeHasBody(route Route) bool {
	if route.Method != "POST" && route.Method != "PUT" && route.Method != "PATCH" {
		return false
	}
	normalized := NormalizeEchoPath(route.Path)
	switch {
	case strings.HasSuffix(normalized, "/disable"),
		strings.HasSuffix(normalized, "/enable"),
		strings.HasSuffix(normalized, "/publish"),
		strings.HasSuffix(normalized, "/test"),
		strings.HasSuffix(normalized, "/test-send"),
		strings.HasSuffix(normalized, "/auto-provision-tracking"),
		strings.HasSuffix(normalized, "/identities/sync"),
		strings.Contains(normalized, "/set-default"),
		normalized == "/api/v1/webhooks/ses/inbound":
		return false
	default:
		return true
	}
}

func routeParameters(route Route) []operationParam {
	params := make([]operationParam, 0, len(route.Parameters)+2)
	for _, p := range route.Parameters {
		params = append(params, operationParam{
			Name:        p,
			In:          "path",
			Type:        "string",
			Required:    true,
			Description: fmt.Sprintf("%s path parameter", p),
		})
	}

	if routeSupportsCursor(route) {
		params = append(params,
			operationParam{Name: "cursor", In: "query", Type: "string", Required: false, Description: "Pagination cursor"},
			operationParam{Name: "limit", In: "query", Type: "integer", Required: false, Description: "Page size"},
		)
	}

	return params
}

func routeSupportsCursor(route Route) bool {
	if route.Method != "GET" {
		return false
	}
	normalized := NormalizeEchoPath(route.Path)
	switch {
	case normalized == "/health",
		normalized == "/healthz",
		normalized == "/metrics",
		normalized == "/public/video-thumbnail",
		strings.HasPrefix(normalized, "/t/o/"),
		strings.HasSuffix(normalized, "/events"),
		strings.Contains(normalized, "/versions/{version_id}/locales"),
		strings.HasSuffix(normalized, "/dashboard-stats"),
		strings.HasSuffix(normalized, "/setup-guide"),
		strings.HasSuffix(normalized, "/status"),
		normalized == "/api/v1/members/me":
		return false
	}
	return strings.HasSuffix(normalized, "/emails") ||
		strings.HasSuffix(normalized, "/tenants") ||
		strings.HasSuffix(normalized, "/workspaces") ||
		strings.HasSuffix(normalized, "/members") ||
		strings.HasSuffix(normalized, "/adapters") ||
		strings.HasSuffix(normalized, "/api-keys") ||
		strings.HasSuffix(normalized, "/template-types") ||
		strings.HasSuffix(normalized, "/templates") ||
		strings.HasSuffix(normalized, "/webhooks") ||
		strings.HasSuffix(normalized, "/audit-log")
}

func routeTag(route Route) string {
	normalized := NormalizeEchoPath(route.Path)
	switch {
	case normalized == "/health" || normalized == "/healthz" || normalized == "/metrics":
		return "health"
	case strings.HasPrefix(normalized, "/t/o/"):
		return "tracking"
	case normalized == "/public/video-thumbnail":
		return "media"
	case normalized == "/api/v1/send", normalized == "/api/v1/send/batch":
		return "send"
	case strings.HasPrefix(normalized, "/api/v1/emails"):
		return "emails"
	case strings.HasPrefix(normalized, "/api/v1/onboarding"):
		return "onboarding"
	case strings.HasPrefix(normalized, "/api/v1/manage/tenants") && strings.Contains(normalized, "/workspaces") && strings.Contains(normalized, "/adapters") && strings.Contains(normalized, "/identities"):
		return "adapter-identities"
	case strings.Contains(normalized, "/adapters") && strings.Contains(normalized, "/identities"):
		return "adapter-identities"
	case strings.Contains(normalized, "/adapters"):
		return "adapters"
	case strings.Contains(normalized, "/template-types"):
		return "template-types"
	case strings.Contains(normalized, "/templates"):
		return "templates"
	case strings.Contains(normalized, "/injectors"):
		return "injectors"
	case strings.Contains(normalized, "/api-keys"):
		return "api-keys"
	case strings.Contains(normalized, "/webhooks"):
		return "webhooks"
	case strings.Contains(normalized, "/suppression"):
		return "suppression"
	case strings.Contains(normalized, "/audit-log"):
		return "audit"
	case strings.Contains(normalized, "/dashboard-stats"):
		return "dashboard"
	case strings.Contains(normalized, "/workspaces"):
		return "workspaces"
	case strings.Contains(normalized, "/members"):
		return "members"
	case strings.Contains(normalized, "/config"):
		return "config"
	case strings.Contains(normalized, "/tenants"):
		return "tenants"
	default:
		return "public"
	}
}

func routeSecurity(route Route) []string {
	normalized := NormalizeEchoPath(route.Path)
	switch {
	case normalized == "/health",
		normalized == "/healthz",
		normalized == "/metrics",
		normalized == "/api/v1/onboarding/status",
		normalized == "/api/v1/webhooks/ses/inbound",
		strings.HasPrefix(normalized, "/t/o/"),
		normalized == "/public/video-thumbnail":
		return nil
	case strings.HasPrefix(normalized, "/api/v1/manage/"),
		normalized == "/api/v1/members/me",
		normalized == "/api/v1/onboarding/setup":
		return []string{"ManagementBearer"}
	case normalized == "/api/v1/send",
		normalized == "/api/v1/send/batch",
		strings.HasPrefix(normalized, "/api/v1/emails"):
		return []string{"WorkspaceAPIKeyBearer"}
	default:
		return nil
	}
}

func routeRequestType(route Route) string {
	normalized := NormalizeEchoPath(route.Path)
	switch normalized {
	case "/api/v1/send":
		return "request.SendEmailRequest"
	case "/api/v1/send/batch":
		return "request.SendBatchRequest"
	case "/api/v1/manage/tenants/{tenant_code}/workspaces/{workspace_code}/templates/{template_id}/bulk-send":
		return "request.TemplateBulkSendRequest"
	case "/api/v1/onboarding/setup":
		return "request.OnboardingSetupRequest"
	case "/api/v1/manage/tenants":
		if route.Method == "POST" {
			return "request.CreateTenantRequest"
		}
	case "/api/v1/manage/tenants/{tenant_code}":
		if route.Method == "PUT" {
			return "request.UpdateTenantRequest"
		}
	case "/api/v1/manage/tenants/{tenant_code}/workspaces":
		if route.Method == "POST" {
			return "request.CreateWorkspaceRequest"
		}
	case "/api/v1/manage/tenants/{tenant_code}/workspaces/{workspace_code}":
		if route.Method == "PUT" {
			return "request.UpdateWorkspaceRequest"
		}
	case "/api/v1/manage/members":
		if route.Method == "POST" {
			return "request.CreateMemberRequest"
		}
	case "/api/v1/manage/members/{member_id}/roles":
		if route.Method == "POST" {
			return "request.AddRoleRequest"
		}
	case "/api/v1/manage/config":
		if route.Method == "PUT" {
			return "request.UpdateConfigRequest"
		}
	}

	switch {
	case strings.HasSuffix(normalized, "/injectors") && route.Method == "POST":
		return "request.CreateInjectorRequest"
	case strings.HasSuffix(normalized, "/injectors/{name}/fields/{field_name}") && route.Method == "PUT":
		return "request.UpdateInjectorFieldRequest"
	case strings.HasSuffix(normalized, "/injectors/{name}/values") && route.Method == "PUT":
		return "request.SetInjectorValuesRequest"
	case strings.HasSuffix(normalized, "/adapters") && route.Method == "POST":
		return "request.CreateAdapterRequest"
	case strings.Contains(normalized, "/adapters/{id}") && route.Method == "PUT" && !strings.HasSuffix(normalized, "/identities/{identity_id}/set-default"):
		return "request.UpdateAdapterRequest"
	case strings.HasSuffix(normalized, "/adapters/{id}/identities") && route.Method == "POST":
		return "request.CreateManualIdentityRequest"
	case strings.HasSuffix(normalized, "/template-types") && route.Method == "POST":
		return "request.CreateTemplateTypeRequest"
	case strings.HasSuffix(normalized, "/templates") && route.Method == "POST":
		return "request.CreateTemplateRequest"
	case strings.HasSuffix(normalized, "/versions") && route.Method == "POST":
		return "request.CreateVersionRequest"
	case strings.Contains(normalized, "/versions/{version_id}") && route.Method == "PUT" && !strings.Contains(normalized, "/locales/"):
		return "request.CreateVersionRequest"
	case strings.Contains(normalized, "/locales/{locale}") && (route.Method == "POST" || route.Method == "PUT"):
		return "request.SetLocaleRequest"
	case strings.HasSuffix(normalized, "/preview-mjml") && route.Method == "POST":
		return "request.MJMLPreviewRequest"
	case strings.HasSuffix(normalized, "/webhooks") && route.Method == "POST":
		return "request.CreateWebhookRequest"
	case strings.Contains(normalized, "/webhooks/{id}") && route.Method == "PUT":
		return "request.UpdateWebhookRequest"
	case strings.HasSuffix(normalized, "/api-keys") && route.Method == "POST":
		return "request.CreateAPIKeyRequest"
	case strings.HasSuffix(normalized, "/suppression") && route.Method == "POST":
		return "request.AddSuppressionRequest"
	default:
		return ""
	}
}

func routeSuccessType(route Route) string {
	normalized := NormalizeEchoPath(route.Path)
	switch normalized {
	case "/health", "/healthz":
		return "DocHealthResponse"
	case "/api/v1/send":
		return "response.SendEmailResponse"
	case "/api/v1/send/batch":
		return "response.SendBatchResponse"
	case "/api/v1/manage/tenants/{tenant_code}/workspaces/{workspace_code}/templates/{template_id}/bulk-send":
		return "response.SendBatchResponse"
	case "/api/v1/manage/tenants/{tenant_code}/workspaces/{workspace_code}/templates/{template_id}/bulk-send-config":
		return "response.TemplateBulkSendConfigResponse"
	case "/api/v1/onboarding/status":
		return "response.OnboardingStatusResponse"
	case "/api/v1/onboarding/setup":
		return "response.OnboardingSetupResponse"
	case "/api/v1/manage/config":
		return "response.ConfigResponse"
	case "/api/v1/members/me":
		return "response.MemberWithRolesResponse"
	case "/api/v1/manage/tenants":
		if route.Method == "GET" {
			return "response.TenantListResponse"
		}
		if route.Method == "POST" {
			return "response.TenantResponse"
		}
	case "/api/v1/manage/tenants/{tenant_code}":
		return "response.TenantResponse"
	case "/api/v1/manage/tenants/{tenant_code}/workspaces":
		if route.Method == "GET" {
			return "response.WorkspaceListResponse"
		}
		if route.Method == "POST" {
			return "response.WorkspaceResponse"
		}
	case "/api/v1/manage/tenants/{tenant_code}/workspaces/{workspace_code}":
		return "response.WorkspaceResponse"
	case "/api/v1/manage/members":
		if route.Method == "GET" {
			return "response.MemberListResponse"
		}
		if route.Method == "POST" {
			return "response.MemberResponse"
		}
	case "/api/v1/manage/members/{member_id}":
		return "response.MemberWithRolesResponse"
	case "/api/v1/manage/members/{member_id}/roles":
		return "response.MemberRoleResponse"
	case "/api/v1/emails":
		return "response.EmailListResponse"
	case "/api/v1/emails/{tracking_id}":
		return "response.EmailDetailResponse"
	case "/api/v1/emails/{tracking_id}/events":
		return "response.EmailEventResponse"
	}

	switch {
	case strings.HasSuffix(normalized, "/emails"):
		return "response.EmailListResponse"
	case strings.HasSuffix(normalized, "/emails/{tracking_id}"):
		return "response.EmailDetailResponse"
	case strings.HasSuffix(normalized, "/emails/{tracking_id}/events"):
		return "response.EmailEventResponse"
	case strings.HasSuffix(normalized, "/injectors") && route.Method == "GET":
		return "response.InjectorListResponse"
	case strings.HasSuffix(normalized, "/injectors") && route.Method == "POST":
		return "response.InjectorDetailResponse"
	case strings.HasSuffix(normalized, "/injectors/{name}/fields/{field_name}") && route.Method == "PUT":
		return "response.InjectorFieldResponse"
	case strings.Contains(normalized, "/injectors/{name}") && route.Method == "GET":
		return "response.InjectorDetailResponse"
	case strings.HasSuffix(normalized, "/adapters") && route.Method == "GET":
		return "response.AdapterListResponse"
	case strings.HasSuffix(normalized, "/adapters") && route.Method == "POST":
		return "response.AdapterResponse"
	case strings.Contains(normalized, "/adapters/{id}") && route.Method == "GET":
		return "response.AdapterResponse"
	case strings.Contains(normalized, "/adapters/{id}") && route.Method == "PUT":
		return "response.AdapterResponse"
	case strings.HasSuffix(normalized, "/adapters/{id}/identities") && route.Method == "GET":
		return "response.AdapterIdentityResponse"
	case strings.HasSuffix(normalized, "/adapters/{id}/identities") && route.Method == "POST":
		return "response.AdapterIdentityResponse"
	case strings.HasSuffix(normalized, "/template-types") && route.Method == "GET":
		return "response.TemplateTypeListResponse"
	case strings.HasSuffix(normalized, "/template-types") && route.Method == "POST":
		return "response.TemplateTypeResponse"
	case strings.Contains(normalized, "/template-types/{slug}") && route.Method == "GET" && !strings.Contains(normalized, "/templates"):
		return "response.TemplateTypeResponse"
	case strings.HasSuffix(normalized, "/template-types/{slug}/templates"):
		return "response.TemplateListResponse"
	case strings.HasSuffix(normalized, "/templates") && route.Method == "POST":
		return "response.TemplateResponse"
	case strings.HasSuffix(normalized, "/versions") && route.Method == "GET":
		return "response.TemplateVersionListResponse"
	case strings.HasSuffix(normalized, "/versions") && route.Method == "POST":
		return "response.TemplateVersionResponse"
	case strings.Contains(normalized, "/versions/{version_id}") && route.Method == "GET" && !strings.Contains(normalized, "/locales/"):
		return "response.TemplateVersionResponse"
	case strings.Contains(normalized, "/versions/{version_id}") && route.Method == "PUT" && !strings.Contains(normalized, "/locales/"):
		return "response.TemplateVersionResponse"
	case strings.HasSuffix(normalized, "/versions/{version_id}/locales"):
		return "DocTemplateLocaleListResponse"
	case strings.Contains(normalized, "/locales/{locale}") && (route.Method == "GET" || route.Method == "POST" || route.Method == "PUT"):
		return "response.TemplateVersionLocaleResponse"
	case strings.HasSuffix(normalized, "/preview-mjml"):
		return "response.MJMLPreviewResponse"
	case strings.HasSuffix(normalized, "/api-keys") && route.Method == "GET":
		return "response.APIKeyListResponse"
	case strings.HasSuffix(normalized, "/api-keys") && route.Method == "POST":
		return "response.APIKeyCreatedResponse"
	case strings.HasSuffix(normalized, "/webhooks") && route.Method == "GET":
		return "response.WebhookListResponse"
	case strings.HasSuffix(normalized, "/webhooks") && route.Method == "POST":
		return "response.WebhookCreatedResponse"
	case strings.Contains(normalized, "/webhooks/{id}") && route.Method == "GET":
		return "response.WebhookResponse"
	case strings.Contains(normalized, "/webhooks/{id}") && route.Method == "PUT":
		return "response.WebhookResponse"
	case strings.HasSuffix(normalized, "/webhooks/{id}/test"):
		return "DocStatusResponse"
	case strings.HasSuffix(normalized, "/suppression") && route.Method == "POST":
		return "response.SuppressionWorkspaceResponse"
	case strings.Contains(normalized, "/suppression/{email}") && route.Method == "GET":
		return "response.SuppressionCheckResponse"
	case strings.HasSuffix(normalized, "/audit-log"):
		return "response.AuditLogListResponse"
	case strings.HasSuffix(normalized, "/dashboard-stats"):
		return "response.DashboardStatsResponse"
	default:
		return "DocGenericObject"
	}
}

func routeSuccessStatus(route Route) int {
	normalized := NormalizeEchoPath(route.Path)
	switch route.Method {
	case "POST":
		switch {
		case normalized == "/api/v1/send",
			normalized == "/api/v1/send/batch",
			normalized == "/api/v1/manage/tenants/{tenant_code}/workspaces/{workspace_code}/templates/{template_id}/bulk-send":
			return 202
		case strings.HasSuffix(normalized, "/setup"),
			strings.HasSuffix(normalized, "/tenants"),
			strings.HasSuffix(normalized, "/workspaces"),
			strings.HasSuffix(normalized, "/members"),
			strings.HasSuffix(normalized, "/roles"),
			strings.HasSuffix(normalized, "/injectors"),
			strings.HasSuffix(normalized, "/adapters"),
			strings.HasSuffix(normalized, "/identities"),
			strings.HasSuffix(normalized, "/template-types"),
			strings.HasSuffix(normalized, "/templates"),
			strings.HasSuffix(normalized, "/versions"),
			strings.Contains(normalized, "/locales/{locale}"),
			strings.HasSuffix(normalized, "/api-keys"),
			strings.HasSuffix(normalized, "/webhooks"),
			strings.HasSuffix(normalized, "/suppression"):
			return 201
		}
	case "DELETE":
		return 204
	}

	switch {
	case strings.HasSuffix(normalized, "/disable"),
		strings.HasSuffix(normalized, "/enable"),
		strings.HasSuffix(normalized, "/publish"),
		strings.HasSuffix(normalized, "/identities/{identity_id}/set-default"),
		strings.HasSuffix(normalized, "/identities/sync"),
		strings.HasSuffix(normalized, "/api-keys/{id}"),
		strings.HasSuffix(normalized, "/suppression/{email}"):
		return 204
	default:
		return 200
	}
}

func operationFuncName(route Route) string {
	raw := strings.ToLower(route.Method + "_" + strings.Trim(route.Path, "/"))
	replacer := strings.NewReplacer("/", "_", ":", "", "-", "_", ".", "_")
	raw = replacer.Replace(raw)
	if raw == "" {
		raw = "root"
	}
	return "doc_" + raw
}

// ConvertSwaggerToOpenAPI converts a swagger v2 file produced by swag into OpenAPI 3 and
// normalizes the security schemes for MCP consumption.
func ConvertSwaggerToOpenAPI(swaggerPath, outPath string) error {
	data, err := os.ReadFile(swaggerPath)
	if err != nil {
		return fmt.Errorf("read swagger: %w", err)
	}

	var raw any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return fmt.Errorf("parse swagger yaml: %w", err)
	}
	jsonData, err := json.Marshal(raw)
	if err != nil {
		return fmt.Errorf("marshal swagger yaml to json: %w", err)
	}

	var swagger openapi2.T
	if err := swagger.UnmarshalJSON(jsonData); err != nil {
		return fmt.Errorf("parse swagger: %w", err)
	}
	doc, err := openapi2conv.ToV3(&swagger)
	if err != nil {
		return fmt.Errorf("convert swagger to openapi: %w", err)
	}

	PatchSecuritySchemes(doc)

	out, err := yaml.Marshal(doc)
	if err != nil {
		return fmt.Errorf("marshal openapi: %w", err)
	}
	if err := os.WriteFile(outPath, out, 0o644); err != nil {
		return fmt.Errorf("write openapi: %w", err)
	}
	return nil
}

// LoadOpenAPI loads an OpenAPI 3 document from disk.
func LoadOpenAPI(path string) (*openapi3.T, error) {
	loader := openapi3.NewLoader()
	doc, err := loader.LoadFromFile(path)
	if err != nil {
		return nil, fmt.Errorf("load openapi: %w", err)
	}
	return doc, nil
}

// PatchSecuritySchemes rewrites the generated schemes into explicit bearer schemes.
func PatchSecuritySchemes(doc *openapi3.T) {
	if doc == nil {
		return
	}
	if doc.Components.SecuritySchemes == nil {
		doc.Components.SecuritySchemes = openapi3.SecuritySchemes{}
	}

	doc.Components.SecuritySchemes["ManagementBearer"] = &openapi3.SecuritySchemeRef{
		Value: &openapi3.SecurityScheme{
			Type:         "http",
			Scheme:       "bearer",
			BearerFormat: "JWT",
			Description:  "OIDC bearer token for Senda management endpoints.",
		},
	}

	doc.Components.SecuritySchemes["WorkspaceAPIKeyBearer"] = &openapi3.SecuritySchemeRef{
		Value: &openapi3.SecurityScheme{
			Type:         "http",
			Scheme:       "bearer",
			BearerFormat: "senda_live",
			Description:  "Workspace-scoped API key sent as Authorization: Bearer senda_live_...",
		},
	}
}

// ValidateRouteCoverage ensures every registered route is present in the OpenAPI document.
func ValidateRouteCoverage(doc *openapi3.T, routes []Route) error {
	if doc == nil {
		return fmt.Errorf("openapi document is nil")
	}

	specOps := make(map[string]struct{})
	if doc.Paths != nil {
		for path, item := range doc.Paths.Map() {
			for method := range pathItemOperations(item) {
				specOps[strings.ToUpper(method)+" "+path] = struct{}{}
			}
		}
	}

	var missing []string
	for _, route := range routes {
		key := route.Method + " " + NormalizeEchoPath(route.Path)
		if _, ok := specOps[key]; !ok {
			missing = append(missing, key)
		}
	}

	if len(missing) > 0 {
		sort.Strings(missing)
		return fmt.Errorf("routes missing from OpenAPI: %s", strings.Join(missing, ", "))
	}
	return nil
}

func pathItemOperations(item *openapi3.PathItem) map[string]*openapi3.Operation {
	ops := map[string]*openapi3.Operation{}
	if item == nil {
		return ops
	}
	if item.Get != nil {
		ops["GET"] = item.Get
	}
	if item.Post != nil {
		ops["POST"] = item.Post
	}
	if item.Put != nil {
		ops["PUT"] = item.Put
	}
	if item.Delete != nil {
		ops["DELETE"] = item.Delete
	}
	if item.Patch != nil {
		ops["PATCH"] = item.Patch
	}
	if item.Head != nil {
		ops["HEAD"] = item.Head
	}
	if item.Options != nil {
		ops["OPTIONS"] = item.Options
	}
	return ops
}
